
services:
  
  db:
    image: postgres:15.2
    restart: always
    volumes:
      - shop-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

    ports:
      - "5430:5432"

volumes:
  shop-db:
    external: false
